services:
  - type: web
    name: medical-ai-chatbot-api
    runtime: python
    repo: https://github.com/SahilOtavanekar/A-Multimodal-AI-Medical-Chatbot-for-Symptom-Interpretation-and-Health-Awareness
    branch: master
    rootDir: frontend/api/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
